#----------------DEV Environment----------------
# [Server]
server:
  address: 127.0.0.1
  port: 8080 # 服务绑定的端口，不写默认是8080
  servlet:
    context-path: /demo # 服务的路径，不写默认为空
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8
